# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3
  # Node 18+ requires GLIBC 2.18 which is only available by default in
  # Ubuntu 18.10+. Fix to Node 17 while we still use Ubuntu 18.04.
  node: 17.0.0

default_stages: [Nonepre-commitNone]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.23.2
    hooks:
      - id: gitleaks-docker
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: _pb2\.py$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [markdown]
        args: [--embedded-language-formatting=off, --prose-wrap=always]
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.3
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt-docker
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        # pre-commit requires that we split args at whitespce boundaries.
        args: [
          --style, .style.yapf,
          -i,
          -e, '*pb2.py',
          -e, '*pb2_grpc.py',
          -e, '*eggs*.py',
          -e, '*env*',
          -e, 'build/*'
        ]
        exclude: '\w*pb2.py'
        additional_dependencies: [toml]
